#!/bin/bash
#called from 5populate-rootfs
#enter with $1=generic-name, $2=compat-name, $3=path to expanded pkg
#ex: acl, void, ${E1}/sandbox/acl-1.2.3_1.x86_64
#ex: sysvinit-utils-cut oe ${E1}/sandbox/sysvinit-3.01-r6-nocona-64
#20240318

Egeneric="$1"
export Ecompatname="$2" #exs: void oe
Pdir="$3"

RP="$(realpath ${0})"
L1="${RP/buildquantumvis*/buildquantumvis}"
xARCH="$(arch)"
. /var/local/woofQV/VARS #has E1

L2="${L1}/pkg-fix/packages-templates"
[ ! -d ${L2}/${Egeneric} ] && exit 1 #precaution

. ${L1}/configure/${xARCH}/DISTRO_SPECS

echo "Applying template fix to ${Pdir##*/}"
cd ${Pdir}
if [ -f ${L2}/${Egeneric}/FIXUPHACK ];then
. ${L2}/${Egeneric}/FIXUPHACK
fi

#20240223 no, now handled in 5populate-rootfs...
#if [ -f ${L2}/${Egeneric}/pinstall.sh ];then
# cp -a -f ${L2}/${Egeneric}/pinstall.sh ${Pdir}/
#fi

if [ "$DISABLE_POST_INSTALL_SCRIPT" == "yes" ];then #this may be in FIXUPHACK
 if [ -f ${Pdir}/INSTALL ];then
  rm -f ${Pdir}/INSTALL
 fi
fi

#20240313 no, now handled in 5populate-rootfs...
#if [ -d ${L2}/${Egeneric}/REPLACEMENTS ];then
# cp -a -f --remove-destination ${L2}/${Egeneric}/REPLACEMENTS/* ${Pdir}/
#fi

###end###
