#!/bin/ash
#called from 5populate-rootfs
#also in running QV from /usr/local/petget/installpkg.sh and support/pet2xbps
#$1 expanded pkg folder, $2 temp usrmerge-fixed folder.
#need to be in same path as $1 and $2

#$F2 will have copy of $F1 except with usr-merge.
F1="$1"; F2="$2"

if [ ! -d "$F1" -o ! -d "$F2" ];then
 echo "ERROR: usrmerge-fix: folder does not exist"
 exit 1
fi

RP="$(realpath ${0})"
if [ "${RP/*buildquantumvis*/yes}" == "yes" ];then
 #running in woofQV
 L1="${RP/buildquantumvis*/buildquantumvis}"
 RUNNINGWOOF=yes
else
 #running in QV
 L1='/usr/local/petget'
 #...note, woofQV has copied pkg-fix and support folders into /usr/local/petget
 RUNNINGWOOF=no
fi

xARCH="$(arch)"
mkdir -p /tmp/woofQV
. /var/local/woofQV/VARS #has E1

#skeleton with all correct usr-merge symlinks...
rm -rf ./${F2} 2>/dev/null
cp -a ${L1}/pkg-fix/usrmerge-template ${F2}

#we also need to be careful not to write a symlink, say a busybox applet
#that will overwrite an already-installed full utility. see section-B below.
ROOTFS="${E1}/rootfs"

while read aF
do
 if [ -d ${F1}/"$aF" ];then
  #the trailing-slash is important...
  mkdir -p ${F2}/"$aF"/
 else
  aD="$(dirname "$aF")"
  mkdir -p ${F2}/"$aD"/
  if [ -h ${F1}/"$aF" ];then
   #section-B
   if [ -e ${ROOTFS}/"$aF" ];then
    if [ ! -h ${ROOTFS}/"$aF" ];then
     continue
    fi
   fi
  fi
  cp -a --remove-destination ${F1}/"$aF" ${F2}/"$aD"/
 fi
done <<_END1
$(find ${F1} -mindepth 1 | sed -e "s%${F1}/%%")
_END1

###end###
