#!/bin/bash
#called from 4create-wip-dep-order
#create woof-installed-packages and devx-only-installed-packages
#20240318

export LANG=C
xARCH="$(arch)"

RP="$(realpath ${0})"
if [ "${RP/*buildquantumvis*/yes}" == "yes" ];then
 #running in woofQV
 L1="${RP/buildquantumvis*/buildquantumvis}"
 RUNNINGWOOF=yes
. ${L1}/configure/${xARCH}/DISTRO_SPECS
. ${L1}/configure/${xARCH}/DISTRO_PKGS_SPECS
else
 #running in quirky
 L1='/usr/local/petget'
 #...note, woofQV has copied pkg-fix and support folders into /usr/local/petget
 RUNNINGWOOF=no
. /etc/DISTRO_SPECS
. /root/.packages/DISTRO_PKGS_SPECS
fi

mkdir -p /tmp/woofQV
. /var/local/woofQV/VARS #has E1

echo -n '' > ${E1}/woof-installed-packages
#will have matching line (fields 2,3,4,5) from PACKAGES_SPECS_TABLE appended...
echo -n '' > ${E1}/woof-installed-packages-PST
echo -n '' > ${E1}/devx-only-installed-packages
echo -n '' > ${E1}/devx-only-installed-packages-PST

cd /tmp/woofQV
echo -n '' > woof-installed-packages
echo -n '' > woof-installed-packages-PST
echo -n '' > devx-only-installed-packages
echo -n '' > devx-only-installed-packages-PST

echo "Creating woof-installed-packages"

while read aL
do
 Egeneric="$(cut -f 1 -d '|' <<<${aL})" #ex: acl
 Epkgs="$(cut -f 2 -d '|' <<<${aL} | tr ',' ' ')"    #ex: acl,acl-devel
 Esplit="$(cut -f 3 -d '|' <<<${aL})"   #ex: exe,dev,doc,nls
 xEsplit=" ${Esplit//,/ } "
 Erepo="$(cut -f 4 -d '|' <<<${aL})"    #exs: compat:current compat:kirkstone pet:noarch pet:void
 
 case "$Erepo" in
  pet:*)
   #will only have one pkg in Epkgs field. Egeneric is no longer necessarily the actual pkg name.
   [ -z "$Epkgs" ] && continue #precaution.
   aDB="$(grep -h -F "|${Epkgs}|" ${L1}/configure/${xARCH}/Packages-pet-${Erepo#*:}-official)"
   grep -q -E ' exe>dev | dev ' <<<${xEsplit}
   RET1=$?
   if [ $RET1 -eq 0 ];then
    grep -v -q -F 'exe,dev' <<<${Esplit}
    RET1=$?
   fi
   if [ $RET1 -eq 0 ];then
    cat <<<${aDB} >> devx-only-installed-packages
    cat <<<${aDB}${aL} >> devx-only-installed-packages-PST
   else
    cat <<<${aDB} >> woof-installed-packages
    cat <<<${aDB}${aL} >> woof-installed-packages-PST
   fi
   continue
  ;;
 esac
 
 case "$Erepo" in
  compat:*)
   #$Epkgs contains the pkgs...
   for aPKG in ${Epkgs}
   do
    aDB="$(grep -h -F "|${aPKG}|" ${L1}/configure/${xARCH}/Packages-*-${Erepo#*:}* | tail -n 1)"
    #...there should only be one hit. exs: Packages-void-current, Packages-oe-kirkstone-official
    # ex: acl-2.3.1_1|acl|2.3.1|1|BuildingBlock|16K|current|acl-2.3.1_1.x86_64.xbps|+glibc|Access Control List filesystem support|void|current||
    case "$aPKG" in
     *-devel)
      cat <<<${aDB} >> devx-only-installed-packages
      cat <<<${aDB}${aL} >> devx-only-installed-packages-PST
      continue
     ;;
    esac
    #note, kirkstone pkgs are the only one that may be split between exe and dev...
    grep -q -E ' exe>dev | dev ' <<<${xEsplit}
    RET1=$?
    if [ $RET1 -eq 0 ];then
     grep -v -q -F 'exe,dev' <<<${Esplit}
     RET1=$?
    fi
    if [ $RET1 -eq 0 ];then
     cat <<<${aDB} >> devx-only-installed-packages
     cat <<<${aDB}${aL} >> devx-only-installed-packages-PST
    else
     cat <<<${aDB} >> woof-installed-packages
     cat <<<${aDB}${aL} >> woof-installed-packages-PST
    fi
   done
  ;;
 esac

done <<_EOF
$(grep '^yes' <<<${PKGS_SPECS_TABLE} | cut -f 2,3,4,5 -d '|')
_EOF

#a pkg may be more than once (ex: glibc), need -u ...
sort --key=1,1 --field-separator="|" -u woof-installed-packages > ${E1}/woof-installed-packages
if [ -s devx-only-installed-packages ];then
 sort --key=1,1 --field-separator="|" -u devx-only-installed-packages > ${E1}/devx-only-installed-packages
 sed -i '/^$/d' ${E1}/devx-only-installed-packages
fi
sort --key=1,1 --field-separator="|" -u woof-installed-packages-PST > ${E1}/woof-installed-packages-PST
if [ -s devx-only-installed-packages-PST ];then
 sort --key=1,1 --field-separator="|" -u devx-only-installed-packages-PST > ${E1}/devx-only-installed-packages-PST
 sed -i '/^$/d' ${E1}/devx-only-installed-packages-PST
fi
sed -i '/^$/d' ${E1}/woof-installed-packages
sed -i '/^$/d' ${E1}/woof-installed-packages-PST

###end###
