#!/bin/ash
#20220214 insert more menus into the tray.
#20220526 support EOS_SUPPORT_CONTAINERS==0
#20240926 remove $EOS_SUPPORT_CONTAINERS" != "0" code.

export TEXTDOMAIN=ui-jwm
export OUTPUT_CHARSET=UTF-8

. /etc/rc.d/PUPSTATE #20220526 has EOS_SUPPORT_CONTAINERS

if [ ! -f /root/.jwm/tray-menus ];then
 mDRIVES="$(gettext 'Drives')"
 mCONTAINERS="$(gettext 'Containers')"
 echo "		<TrayButton popup=\"${mDRIVES}\" icon=\"drives48.png\">root:2</TrayButton>" > /root/.jwm/tray-menus
fi

#insert file between two patterns in /root/.jwmrc-tray...
sed -i -e '/STARTMENU/,/ENDMENU/{/STARTMENU/!{/ENDMENU/!d}}' -e '/STARTMENU/r /root/.jwm/tray-menus' /root/.jwmrc-tray

###end###
