#!/bin/bash
#call from /etc/rc.d/rc.update
#rc.update calls xbps-user-postupdate, which expects /root/.packages/Packages-
# -void-current & -nonfree to be latest.
#20240318

export LANG=C
RP="$(realpath ${0})"
if [ "${RP/*buildquantumvis*/yes}" == "yes" ];then
 #running in woofQV
 L1="${RP/buildquantumvis*/buildquantumvis}"
 RUNNINGWOOF=yes
else
 #running in quirky
 L1='/usr/local/petget'
 #...note, woofQV has copied pkg-fix and support folders into /usr/local/petget
 RUNNINGWOOF=no
fi

xARCH="$(arch)"
mkdir -p /tmp/woofQV
. /var/local/woofQV/VARS #has E1

. /etc/DISTRO_SPECS

export XBPS_ARCH="$xARCH"

rm -rf /tmp/woofQV/xbps2pupdb 2>/dev/null
mkdir -p /tmp/woofQV/xbps2pupdb
cd /tmp/woofQV/xbps2pupdb

#got code from /usr/local/woofV/support/void0setup...
for aRD in $(find /var/db/xbps -mindepth 2 -maxdepth 2 -type f -name '*-repodata' | tr '\n' ' ')
do
 cp -f ${aRD} ${xARCH}-repodata.tar.zst
 tar --zstd -xf ${xARCH}-repodata.tar.zst
 rm ${xARCH}-repodata.tar.zst
 #remove any utf8 characters...
 iconv -c -f utf-8 -t ascii index.plist > index.plistFIXED
 mv -f index.plistFIXED index.plist
 echo
 ${E1}/support/cvt.sh > pupdb
 grep -q 'nonfree' <<< ${aRD}
 if [ $? -eq 0 ];then
  sed -i -e 's%[|]current[|]%|current/nonfree|%' pupdb
  cp -f pupdb /root/.packages/Packages-void-current-nonfree
 else
  cp -f pupdb /root/.packages/Packages-void-current
 fi
done

###end###
